// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbt_8i7aihcLBs-PWehcRrrc0liCsUvtw',
    appId: '1:553950556862:web:5a7a5cdee93e03f03a24ef',
    messagingSenderId: '553950556862',
    projectId: 'happy2-c2569',
    authDomain: 'happy2-c2569.firebaseapp.com',
    storageBucket: 'happy2-c2569.firebasestorage.app',
    measurementId: 'G-6GW7553H4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI4DV09NW5s1-YJdIe_09N98YMcbAS5gQ',
    appId: '1:553950556862:android:3b53d27860be8b373a24ef',
    messagingSenderId: '553950556862',
    projectId: 'happy2-c2569',
    storageBucket: 'happy2-c2569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvT4DYKuJdkrX-XcaRiQcKRaXu0mqvCM4',
    appId: '1:553950556862:ios:748926d76ae693393a24ef',
    messagingSenderId: '553950556862',
    projectId: 'happy2-c2569',
    storageBucket: 'happy2-c2569.firebasestorage.app',
    iosBundleId: 'com.example.soilHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvT4DYKuJdkrX-XcaRiQcKRaXu0mqvCM4',
    appId: '1:553950556862:ios:748926d76ae693393a24ef',
    messagingSenderId: '553950556862',
    projectId: 'happy2-c2569',
    storageBucket: 'happy2-c2569.firebasestorage.app',
    iosBundleId: 'com.example.soilHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbt_8i7aihcLBs-PWehcRrrc0liCsUvtw',
    appId: '1:553950556862:web:ac115f39c17127b03a24ef',
    messagingSenderId: '553950556862',
    projectId: 'happy2-c2569',
    authDomain: 'happy2-c2569.firebaseapp.com',
    storageBucket: 'happy2-c2569.firebasestorage.app',
    measurementId: 'G-H9WC6NBH6N',
  );
}
